* Create NumPy arrays and perform:
  * Element-wise addition
  * Element-wise multiplication
  * Scalar multiplication
* Experiment with broadcasting using arrays of different shapes.
* Use "np.linalg.eig()" on at least two 2×2 matrices.
* Print and interpret the eigenvalues and eigenvectors obtained.
* Observe how changing matrix values affects the eigenvalues.

In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

In [3]:
print("Array A:", A)
print("\nArray B:", B)

Array A: [1 2 3]

Array B: [4 5 6]


1. add
2. multi. elem. wise
3. scalar multi. 

In [5]:
#1.
print(A + B)


[5 7 9]


In [6]:
#2.
print(A * B)


[ 4 10 18]


In [7]:
#3.
print(5 * A)


[ 5 10 15]


# Broadcasting


In [8]:
matrix = np.array([[1,2,3],[4,5,6]])

In [ ]:
vector = np.array([10,20,30])

In [10]:
print(matrix + vector)#brodcasting


[[11 22 33]
 [14 25 36]]


# Eigenvalues and Eigenvectors


In [12]:
C = np.array([[2,0],[0,3]])

In [13]:
values1, vectors1 = np.linalg.eig(C)


In [14]:
print(C)

[[2 0]
 [0 3]]


In [23]:
print("Eigenvalues:")
print(values1)
print(" ")
print("Eigenvectors:")
print(vectors1)

Eigenvalues:
[2. 3.]
 
Eigenvectors:
[[1. 0.]
 [0. 1.]]


In [17]:
D = np.array([[4,1],[2,3]])

In [ ]:
values2, vectors2 = np.linalg.eig(D)

In [20]:
print(D)

[[4 1]
 [2 3]]


In [22]:
print("Eigenvalues:")
print(values2)
print(" ")
print("Eigenvectors:")
print(vectors2)

Eigenvalues:
[5. 2.]
 
Eigenvectors:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
