Python:

* Use NumPy to create at least three matrices.
* Perform and print:
  * Matrix addition
  * Matrix subtraction
  * Matrix multiplication using np.dot() or the @ operator
  * Matrix transpose using ".T"
* Create an identity matrix using "np.eye()".
* Find the inverse of a valid matrix using "np.linalg.inv()".
* Experiment with matrices of different dimensions and note which operations are valid and which produce errors.

In [ ]:
import numpy as np

In [2]:
A = np.array([[1, 2],[3, 4]])

In [5]:
print("Matrix A:")
print(A)

Matrix A:
[[1 2]
 [3 4]]


In [3]:
B = np.array([[5, 6],[7, 8]])

In [6]:
print("Matrix B:")
print(B)

Matrix B:
[[5 6]
 [7 8]]


In [ ]:
C = np.array([[2, 0],[1, 2]])

In [8]:
print("Matrix C:")
print(C)

Matrix C:
[[2 0]
 [1 2]]


* OPERATIONS
1. A+B
2. B-A
3. AB (MATRIX MULT.)
4. TRANSPOSE OF A AND B
5. IDENTITY OF 3X3
6. INVERSE OF MATRIX 


In [9]:
# 1.
print(A+B)

[[ 6  8]
 [10 12]]


In [10]:
# 2.
print(B-A)

[[4 4]
 [4 4]]


In [12]:
# 3.
print(A @ B)


[[19 22]
 [43 50]]


In [14]:
# 4.
print(A.T)
print(" ")
print(B.T)

[[1 3]
 [2 4]]
 
[[5 7]
 [6 8]]


In [15]:
# 5.
print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#6
print(np.linalg.inv(A))


[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
print(np.linalg.inv(B))


[[-4.   3. ]
 [ 3.5 -2.5]]
